export const THEME = {
    darkest: "#1D1D1D",
    dark: "#BCBCBC",
    light: "#D6D6D6",
    white: "#FFFFFF",
    selectionBg: "#E2E2E2",
    hint: "#A0A0A0",
    stacked: "#BEBEBE",
} as const;


export const FONTS = {
    karlaLight: "fonts/Karla-Light.ttf",
    karlaExtraBold: "fonts/Karla-ExtraBold.ttf",
} as const;

export const CONFIG = {
    loader: {
        REVEAL_DURATION: 0.5,
        ODOMETER_DURATION: 2,
    },
    model: {
        BASE_MODEL_Y: 0.1,
        INTERACTION_LOCK_EPSILON: 0.001,
        MODEL_UP_TRAVEL_FACTOR: 0.25,
        SCALE_OUT_START: 0.2,
        SCALE_OUT_END: 0.9,
        RETURN_TO_CENTER_SMOOTHNESS: 8,
        RETURN_VELOCITY_DAMPING: 10,
        RETURN_SNAP_EPSILON: 0.002,
        DETAILS_POPUP_START: 0.9,
        DETAILS_POPUP_END: 1.0,
        DETAILS_POPUP_SCALE: 0.6,
        DETAILS_POPUP_X_FACTOR: 0.13,
        DETAILS_POPUP_Y_SECTION_OFFSET: 1.1,
        IDLE_ROTATION_SPEED_Z: 1.2,
        IDLE_ROTATION_SPEED_X_MAG: 0.2,
        IDLE_ROTATION_SPEED_Y_MAG: 0.1,
        IDLE_ROTATION_SPEED: 2,
    },
    detailsLayout: {
        SCROLL_TRIGGER_END: "+=50%",
        HEADING_SIZE_MULT: 0.03,
        BODY_SIZE_MULT: 0.5,
        SECTION_TRAVEL_MULT: 1.16,
        TARGET_BASE_Y_MULT: -0.25,
        SECTION_TOP_OFF_MULT: 0.35,
        SECTION_SPACING_MULT: 0.25,
        RIGHT_TITLE_OFFSET_MULT: 0.2,
        GAP_MULT: 0.08,
        BODY_TOP_OFFSET_MULT: 0.38,
        BODY_LINE_HEIGHT_MULT: 1.5,
    },
    detailsTimings: {
        EXPERIENCE_HEADING_DELAY: 0.1,
        EXPERIENCE_BODY_DELAY: 0.18,
        PROJECTS_HEADING_DELAY: 0.3,
        PROJECTS_BODY_DELAY: 0.38,
        EDUCATION_HEADING_DELAY: 0.5,
        EDUCATION_BODY_DELAY: 0.58,
        SKILLS_HEADING_DELAY: 0.12,
        SKILLS_BODY_DELAY: 0.2,
        BODY_STAGGER_STEP: 0.07,
        SKILLS_STAGGER_STEP: 0.06,
    },
    heroText: {
        LABEL_EXIT_START: 0.05,
        LABEL_EXIT_END: 0.1,
    },
    title: {
        TARGET_SCALE: 0.75,
        HINT_SCROLL_HIDE_EPSILON: 0.0005,
        HINT_SCROLL_SHOW_EPSILON: 0.0001,
        STACKED_FADE_START: 0.12,
        VISUAL_FONT_CORRECTION_X: 0.05,
        DELAY_FIRST_RUN: 2.5,
        DURATION_FIRST_RUN: 1.5,
        FADE_DURATION_FIRST_RUN: 1.2,
        FADE_POSITION_FIRST_RUN: 0.8,
    },
    customAberration: {
        COLUMNS: 40.0,
        LERP_FACTOR_MULT: 9.75,
        INTENSITY_LERP_MULT: 3.0,
        INTENSITY_MIN: 0.005,
        SAFE_DELTA_MIN: 0.0001,
        VEL_MULT: 0.016666,
    },
    heroLayout: {
        TITLE_Y_MULTIPLIER: 0.7,
        HERO_Y_MULTIPLIER: 1.05,
        SUBTITLE_Y_MULTIPLIER: 0.22,
        SUBTITLE_PROGRESS_POWER: 1.05,
        TITLE_FONT_SIZE: 0.127,
        TITLE_FONT_VISUAL_OFFSET: 0.14,
        SUBTITLE_FONT_SIZE: 0.03025,
        PROFESSION_FONT_SIZE: 0.02,
        PROFESSION_PADDING_Y: 8,
        PROFESSION_LINE_THICKNESS: 1,
        PROFESSION_LINE_WIDTH: 0.9,
        PROFESSION_EXIT_DISTANCE: 0.14,
    },
    professionLabel: {
        LINE_DELAY: 1.5,
        ALPHA_MULTIPLIER: 0.4,
        LETTER_SPACING: -0.02,
        DELAY: 0.2,
    },
    subtitle: {
        OUTLINE_WIDTH: 0.001,
        LETTER_SPACING: -0.03,
        DELAY: 0.1,
    },
    copy: {
        STAGGER: 0.15,
        DURATION: 0.75,
        LINE_THRESHOLD: 0.1,
    },
} as const;
