export const THEME = {
    darkest: "#1D1D1D",
    dark: "#BCBCBC",
    light: "#D6D6D6",
    white: "#FFFFFF",
    selectionBg: "#E2E2E2",
    hint: "#A0A0A0",
    stacked: "#BEBEBE",
} as const;


export const FONTS = {
    karlaLight: "fonts/Karla-Light.ttf",
    karlaExtraBold: "fonts/Karla-ExtraBold.ttf",
} as const;

const SCROLL_TIMELINE_VIEWPORTS = 1.5;

export const CONFIG = {
    scene: {
        DETAILS_GROUP_Z: -0.05,
    },
    scrollTimeline: {
        VIEWPORTS: SCROLL_TIMELINE_VIEWPORTS,
    },
    loader: {
        REVEAL_DURATION: 0.5,
        ODOMETER_DURATION: 2,
        ODOMETER_DURATION_REPEAT: 0.5,
    },
    model: {
        BASE_MODEL_Y: 0.1,
        INTERACTION_LOCK_EPSILON: 0.07,
        MODEL_UP_TRAVEL_FACTOR: 0.25,
        SCALE_OUT_START: 0.2,
        SCALE_OUT_END: 0.9,
        RETURN_TO_CENTER_SMOOTHNESS: 8,
        RETURN_VELOCITY_DAMPING: 10,
        RETURN_SNAP_EPSILON: 0.002,
        DETAILS_POPUP_START: 0.9,
        DETAILS_POPUP_SCALE: 0.6,
        BIO_FACE_SCALE: 0.16,
        BIO_HANDOFF_SPAN_MULT: 0.6,
        FOLD_FADE_CLEARANCE_MULT: 0.07,
        FOLD_FADE_SPAN_MULT: 0.14,
        POPUP_RAMP_SPAN: 0.1,
        LOOK_BASE_X: 0,
        LOOK_BASE_Y: 0,
        LOOK_BASE_Z: Math.PI,
        LOOK_RANGE_X: 0.45,
        LOOK_RANGE_Y: 0.6,
        LOOK_POINTER_SMOOTHNESS: 6,
        LOOK_SETTLE_SMOOTHNESS: 4,
        IDLE_ROTATION_SPEED_Z: 1.2,
        IDLE_ROTATION_SPEED_X_MAG: 0.2,
        IDLE_ROTATION_SPEED_Y_MAG: 0.1,
        IDLE_ROTATION_SPEED: 2,
        DEPTH_Z: 2,
    },
    detailsLayout: {
        HEADING_SIZE_MULT: 0.03,
        HEADING_MIN_PX: 26,
        HEADING_MAX_PX: 72,
        BODY_SIZE_MULT: 0.5,
        SECTION_TRAVEL_MULT: 1.16,
        TARGET_BASE_Y_MULT: -0.25,
        SECTION_TOP_OFF_MULT: 0.35,
        SECTION_GAP_MULT: 2.4,
        RIGHT_TITLE_OFFSET_MULT: 0.2,
        GAP_MULT: 0.08,
        BODY_TOP_OFFSET_MULT: 0.38,
        BODY_LINE_HEIGHT_MULT: 1.5,
        LETTER_SPACING: -0.03,
        REVEAL_MARGIN_MULT: 0.04,
        BIO_IMAGE_WIDTH_MULT: 0.26,
        BIO_IMAGE_ASPECT: 2000 / 1500,
        BIO_CONTENT_TOP_MULT: 1.75,
        BIO_COLUMN_GAP_MULT: 0.04,
        BIO_REVEAL_LINES: 9,
        BIO_REVEAL_BLOCK_Z: 0.002,
        BIO_REVEAL_BLOCK_OVERHANG: 1.1,
        BIO_REVEAL_BLOCK_RADIUS_PX: 8,
        BIO_FACE_X_MULT: 0.55,
        BIO_FACE_Y_MULT: 0.405,
    },
    detailsReveal: {
        BLOCK_WIDTH_MULT: 1.01,
        BLOCK_HEIGHT_MULT: 1.1,
        BLOCK_RADIUS_PX: 8,
        BLOCK_SEGMENTS: 6,
        BLOCK_Z: 0.002,
    },
    detailsCurl: {
        FOLD_OFFSET_MULT: 0,
        RADIUS_MULT: 0.085,
        MAX_ANGLE: 1.5,
        FADE_ANGLE_START: 0.15,
        FADE_ANGLE_END: 1.25,
        GLYPH_DETAIL: 3,
        ARROW_SEGMENTS: 4,
        IMAGE_SEGMENTS: 24,
    },
    detailsLink: {
        HOVER_COLOR: "#FFFFFF",
        COLOR_DURATION: 0.15,
        ARROW_SIZE_MULT: 0.4,
        ARROW_GAP_MULT: 0.3,
        ARROW_NUDGE_FACTOR: 0.25,
        ARROW_DURATION: 0.2,
        UNDERLINE_PHASE_DURATION: 0.25,
    },
    detailsTimings: {
        HEADING_DELAY: 0.1,
        BODY_DELAY: 0.18,
        BODY_STAGGER_STEP: 0.07,
        SKILLS_STAGGER_STEP: 0.06,
    },
    heroText: {
        LABEL_EXIT_START: 0.05,
        LABEL_EXIT_END: 0.1,
    },
    title: {
        TARGET_SCALE: 0.75,
        HINT_SCROLL_HIDE_EPSILON: 0.0005,
        HINT_SCROLL_SHOW_EPSILON: 0.0001,
        STACKED_FADE_START: 0.12,
        VISUAL_FONT_CORRECTION_X: 0.05,
        DELAY_FIRST_RUN: 2.5,
        DELAY_REPEAT: 0.8,
        DURATION_FIRST_RUN: 1.5,
        FADE_DURATION_FIRST_RUN: 1.2,
        FADE_POSITION_FIRST_RUN: 0.8,
    },
    customAberration: {
        COLUMNS: 40.0,
        LERP_FACTOR_MULT: 9.75,
        INTENSITY_LERP_MULT: 3.0,
        INTENSITY_MIN: 0.005,
        SAFE_DELTA_MIN: 0.0001,
        VEL_MULT: 0.016666,
    },
    heroLayout: {
        TITLE_Y_MULTIPLIER: 0.7,
        HERO_Y_MULTIPLIER: 1.05,
        SUBTITLE_Y_MULTIPLIER: 0.22,
        SUBTITLE_PROGRESS_POWER: 1.05,
        TITLE_FONT_SIZE: 0.127,
        TITLE_FONT_VISUAL_OFFSET: 0.14,
        SUBTITLE_FONT_SIZE: 0.03025,
        PROFESSION_FONT_SIZE: 0.02,
        PROFESSION_PADDING_Y: 8,
        PROFESSION_LINE_THICKNESS: 1,
        PROFESSION_LINE_WIDTH: 0.9,
        PROFESSION_EXIT_DISTANCE: 0.14,
    },
    professionLabel: {
        LINE_DELAY: 1.5,
        ALPHA_MULTIPLIER: 0.4,
        LETTER_SPACING: -0.02,
        DELAY: 0.2,
    },
    subtitle: {
        OUTLINE_WIDTH: 0.001,
        LETTER_SPACING: -0.03,
        DELAY: 0.1,
    },
    copy: {
        STAGGER: 0.15,
        DURATION: 0.75,
        LINE_THRESHOLD: 0.1,
    },
} as const;
